### ISSUE TITLE
Talisman reports error for bash/zsh rc files

### ISSUE THREAD

**Issue by arunvelsriram** [thoughtworks/talisman#117]
It's common to version control configurations like .bashrc, .zshrc, .profile, etc to make new machine setup easier. Recently, `talisman` seem to report an error for changes in these files:

<img width="503" alt="Screenshot 2019-05-24 at 1 09 59 AM" src="https://user-images.githubusercontent.com/6568319/58281405-b5468000-7dc0-11e9-9424-fd9502acde28.png">

Enforcing such things is making the process of versioning configs harder. These files are getting reported even for a small change.

**Comment by harinee** [comment]
Hi @arunvelsriram To get a little info, the bashrc was within a .git folder?

**Comment by arunvelsriram** [comment]
Hi. It's not within `.git` directory. Its version controlled in a git repository.

**Comment by harinee** [comment]
Understood. 
.bashrc, .zshrc etc. are files that may easily contain confidential information that could categorise as secrets, which is why it is added as a test in Talisman.
Any tool, such as Talisman itself, can only predict what could be going wrong. The detectors are to look for common patterns and files where sensitive information can exist. It has to be upto the user to decide that in the context of how the code is set up. 
If you are confident of the content in your file, did you try adding to .talismanrc? (There should have been a helper text right below the message you pasted)
Did that not work?

**Comment by arunvelsriram** [comment]
Of course adding to `.talismanrc` will work. However, it  will reported again for subsequent changes. If a user is confident about a file then they should be able to ignore that file permanently (using something like a `.talismanignore` file).

I have raised a similar concern here as well https://github.com/thoughtworks/talisman/issues/59#issuecomment-480318619

These enforcements may be annoying to users (at least to me). Eventually one might end up removing talisman hook from certain repos which defeats the whole purpose.

**Comment by harinee** [comment]
Talisman's core principle is to prevent accidental checkin of secrets. There are efforts to improve usability in this regard, and we are always looking for suggestions to do so. But I hope you'd agree that the core principle cannot be forgone, which a blanket permanent ignore would encourage.

Issue #122 has been raised to handle permanent ignore as an option for files that are scoped by technology stack, and can be assumed harmless for accidental leakage of secrets.
Please track #122 for further updates on this.

Please do let us know if you have any other suggestions.
