### ISSUE TITLE
make talisman work well with other hooks

### ISSUE THREAD

**Issue by jacksingleton** [thoughtworks/talisman#12]

**Comment by tomdavidson** [comment]
Im curious why pre-push rather than pre-commit?

**Comment by jacksingleton** [comment]
it actually works with pre-commit as well thanks to @jmpak https://github.com/thoughtworks/talisman/pull/3 -- although this is not an option in the installer (yet).

Installing as a pre-push hook means we have to worry less about performance if we add slower detectors in the future.

**Comment by svishwanath-tw** [comment]
@jacksingleton , we currently support using talisman as a [pre-commit](https://pre-commit.com/) hook, you could look at latest Readme on master for more details.
As for talisman by itself playing well with other hooks is demanding too much of it. Breaks SRP (do one thing and do it well)
I personally think, talisman should stick to the standard hook contract (non-zero exit on error) and let a a hook management system like handle the playing well with other hooks part.
What do you think ?

PS: I think a shell based hook management system would be most optimal for this use-case, like [captain-hook](https://github.com/git-hook/captain-hook), since it takes away dependence on another interpreted language like python or node. But ```captain-hook``` is now defunct/un-maintained. (How) Can we address this ?

**Comment by modean** [comment]
Has talisman been tested together with Husky? In other words are there examples providing instructions how to configure both to work together?

https://github.com/typicode/husky

**Comment by harinee** [comment]
@modean Talisman provides support with Husky. Please see https://github.com/thoughtworks/talisman#2-husky-linuxunixwindows

**Comment by harinee** [comment]
@jacksingleton talisman supports working with multiple hooks with pre-commit tool and Husky. Please see https://github.com/thoughtworks/talisman#handling-existing-hooks

If this looks fine, could you please close this issue?

**Comment by modean** [comment]
@harinee ok let my try to configure the provided example in my projects so that I can provide you feedback on whether the results are the one I would expect.

**Comment by harinee** [comment]
Hi @modean Any feedback? If you are happy with the changes, we could close this ticket

**Comment by aaquibzama-tw** [comment]
Hi @modean , could you let us know if you were able to get it working with other hooks. If yes, we could close this ticket.

**Comment by harinee** [comment]
Closing, since we didn't hear any further issues on this. Please feel free to report if issues are faced in this regard
