### ISSUE TITLE
Talisman performing update on every commit

### ISSUE THREAD

**Issue by arunvelsriram** [thoughtworks/talisman#123]
`talisman` is reporting that am using an outdated version and performing the download on every commit(on commit hook) I make. It would make sense to prompt the user for update and perform it once.

```
$ git commit

Your version of Talisman is outdated. Updating Talisman to v0.4.8
Downloading latest talisman binary...
talisman_darwin_amd64: OK

Talisman binary updated successfully!
```

**Comment by harinee** [comment]
Happening with me as well. Just checked.
This is new, because have seen earlier that updates were reported and downloaded only for the first time.
The subsequent ones used to not download Talisman everytime.

@aaquibzama-tw since you had worked on the feature for performing update check, could you please look into this issue?

**Comment by harinee** [comment]
@arunvelsriram 
In the meantime, if this is making your commits slower or annoying, please uninstall and install again. I think that will help keep you to the latest version, and it won't check again (until the next release, of course).
[Disclaimer: haven't tried this myself because I want to keep seeing the issue till it gets fixed. But logically speaking, this should work]

**Comment by arunvelsriram** [comment]
Yes its working after I upgrade to latest version by uninstalling and installing again.

**Comment by dineshba** [comment]
I also faced the same issue. I tried to debug. Here are my findings.

In the `.git/hooks/pre-push` or `.git/hooks/pre-commit`, we have this line
```bash
ORG_REPO=${ORG_REPO:-'thoughtworks/talisman'}
LATEST_VERSION=$(curl -Is https://github.com/${ORG_REPO}/releases/latest | grep -E "Location" | grep -o '[^/]\+$' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
CURRENT_VERSION=$(/Users/dineshbalasubramanian/.talisman/bin/talisman_darwin_amd64 --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
```
the result of this lines is **always**
```bash
$ echo $LATEST_VERSION // 0.4.8
$ echo $CURRENT_VERSION // 0.4.6
```
After upgrading also, the current version is **not getting changed** (which is 0.4.6)

Then I manually downloaded the latest release (tag v0.4.8) from [here](https://github.com/thoughtworks/talisman/releases).
```bash
 ./talisman_darwin_amd64 --v
talisman v0.4.6-32-g136ca89
```
So the **latest build is having wrong version number**
Then I looked into how are we giving the version for the artifact. In `./build` file
```bash
gox -os="linux darwin windows" -arch="386 amd64" -ldflags="-X main.Version=${VERSION}"
```
It looks the `VERSION` environment variable in `travisci` is outdated.

#### Fix: 
We have to update the `VERSION` env variable in travis.

#### Note:
> - I am not very sure how uninstalling and installing fixes the issues. As per my understanding, uninstalling and installing should not fix the issue.
> - Please let me know if I am missing something

**Comment by harinee** [comment]
@dineshba Thanks a ton for the detailed analysis. It helped a lot. 
@aaquibzama-tw has fixed this issue and released.
It should work now (it did for me).
