### ISSUE TITLE
Talisman release 1.8.0 fails to run on MacOS

### ISSUE THREAD

**Issue by svishwanath-tw** [thoughtworks/talisman#242]
**Describe the bug**

If download the release (1.8) of talisman and try to run the executable on MacOS (10.15.*), you see the following error:

```
→ ./talisman_darwin_amd64 
Killed: 9
```

**To Reproduce**
Upgrade to release 1.8

**Expected behavior**
talisman exe should run successfully

**Comment by svishwanath-tw** [comment]
For context, see:

https://github.com/upx/upx/issues/4

https://sourceforge.net/p/upx/bugs/248/

**Comment by harinee** [comment]
There seems to be a binary corruption specifically for darwin, specifically for v1.8.0. A fresh binary has been uploaded again to 1.8.0 release.
If you still face the issue, we request you to:
1. download the talisman_darwin_amd64 binary manually from [releases](https://github.com/thoughtworks/talisman/releases/tag/v1.8.0)
2. on your Mac, navigate to ~/.talisman/bin/ 
3. Replace the existing talisman_darwin_amd64 binary with the manually downloaded binary (from step 1)

**Comment by harinee** [comment]
@dcRUSTy can you help debug this?
Looks like some issue with upx, when built from Travis CI's linux kernel, the binary for darwin doesn't work properly (kills the process, as Suhas has mentioned above)
<img width="540" alt="Screenshot 2020-09-01 at 3 08 56 AM" src="https://user-images.githubusercontent.com/1300665/91831550-d489b980-ec61-11ea-876d-0ef81568617d.png">

If you need any help with testing, feel free to let us know.

MacOSX -- doesn't work
Ubuntu -- works fine
Windows -- works fine

**Comment by dcRUSTy** [comment]
As per log https://travis-ci.org/github/thoughtworks/talisman/builds/723004191 Line 9 Ubuntu Dist is xenial(16.04) and for xenial latest version of upx https://launchpad.net/ubuntu/xenial/+package/upx-ucl is 3.9.1? Which is apparently buggy as per links shared by @svishwanath-tw

**Comment by dcRUSTy** [comment]
Adding a `upx -t talisman_{l,d,w}*`
after
https://github.com/thoughtworks/talisman/blob/648e4563f15f0e2906540396a0426cd88437367d/build#L6
might help a little. The majority(all?) of the issues in which some binaries are corrupt can be detected by -t flag and by running the binary once on CI
and it would be super duper awesome if we can testrun(talisman -v) the downloaded binary in install and update scripts just before replacing the older binary with new one so that user retains the last working version.
![upx_test](https://user-images.githubusercontent.com/40319304/91859322-eed68e00-ec87-11ea-9401-7c53b604b673.JPG)

**Comment by svishwanath-tw** [comment]
@dcRUSTy : The odd thing is. If we build the same thing on mac. The compression percentage values differ and there is no `kill -9` problem with the executable.
